version: '3.8'

services:
  backend:
    build: ./backend
    container_name: kids_learning_backend
    volumes:
      # Mount toàn bộ thư mục backend vào container để giữ lại file data_store.json và learning_app.db
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: kids_learning_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
